name: Generate and Push Appcast

on:
  release:
    types: [published]

jobs:
  generate-appcast:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run appcast generation script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRIVATE_KEY_SECRET: ${{ secrets.PRIVATE_KEY_SECRET }}
        run: |
          chmod +x generate.sh
          ./generate.sh

      - name: Commit and push appcast.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/appcast.xml
          git commit -m "Update appcast.xml for release ${{ github.event.release.tag_name }}"
          git push
